RUN pip3 install torch==0.4.0
RUN pip3 install torchvision==0.2.1
RUN pip3 install pandas==0.23.4
RUN pip3 install opencv-python==4.0.0.21
RUN apt update && apt-get install -y libsm6 libxrender1 libfontconfig1
RUN pip3 install scikit-learn==0.20.2
RUN pip3 install pretrainedmodels==0.7.4
RUN pip3 install pytorchcv==0.0.30
RUN pip3 install albumentations==0.1.11
RUN pip3 install BeautifulSoup4==4.7.1
RUN pip3 install joblib==0.13.1